export type AppConfig = {
  app_name: string;
  host: string;
  port: number;
  model_variants: string[];
  enable_repaint: boolean;
  enable_cover: boolean;
  enable_future_modes: boolean;
  lm_enabled: boolean;
  lm_backend: string;
  lm_checkpoint: string;
  lm_device: string;
  lm_offload_to_cpu: boolean;
  openai_enabled: boolean;
  openai_endpoint: string | null;
  openai_api_key: string | null;
  openai_model: string;
  openai_prompt_system_prompt: string;
  openai_lyrics_system_prompt: string;
  openai_title_system_prompt: string;
  image_generation_provider: "none" | "fal" | "comfy" | "a1111";
  image_prompt_system_prompt: string;
  fal_api_key: string | null;
  comfy_base_url: string | null;
  comfy_workflow_json: string;
  a1111_base_url: string | null;
  data_dirs: Record<string, string>;
  thinking_simple_mode: boolean;
  thinking_custom_mode: boolean;
  use_cot_caption: boolean;
  use_cot_language: boolean;
  use_cot_metas: boolean;
  allow_lm_batch: boolean;
  default_model_variant: string;
  base_inference_steps: number;
  turbo_inference_steps: number;
  shift_inference_steps: number;
  use_adg: boolean;
  cfg_interval_start: number;
  cfg_interval_end: number;
  infer_method: string;
  mps_available: boolean;
  adg_supported: boolean;
  adg_unavailable_reason: string | null;
};
